/*
 * exporters.js — SVG and DXF R12 writers for GearForge Parts.
 *
 * SVG: width/height in real millimetres with a matching viewBox, so it
 * imports mm-true into LightBurn, Inkscape, xTool CS, Glowforge, etc.
 * Layers: <g id="CUT"> (red) and <g id="ENGRAVE"> (blue), stroke-only.
 *
 * DXF: classic R12 POLYLINE/VERTEX/SEQEND (closed flag) + CIRCLE + TEXT on
 * layers CUT/ENGRAVE — the most widely compatible flavour for CAM imports.
 *
 * Kerf compensation is applied here (beam centerline offset kerf/2:
 * outer loops grow, holes shrink). Y is flipped for SVG (screen-down).
 */
(function (global) {
  'use strict';

  const GEO = (typeof module !== 'undefined' && module.exports)
    ? require('./geometry.js')
    : global.GearForge.geometry;

  const N = v => (Math.round(v * 10000) / 10000).toString();

  /** Apply kerf to all cut loops of a part; returns loops (engrave untouched). */
  function kerfLoops(part, kerf) {
    return part.cut.map(loop => {
      const off = GEO.offsetLoopForKerf(loop, kerf || 0);
      if (loop.circleHint && kerf) {
        off.circleHint = {
          cx: loop.circleHint.cx, cy: loop.circleHint.cy,
          r: loop.circleHint.r + (loop.isHole ? -kerf / 2 : kerf / 2),
        };
      } else off.circleHint = loop.circleHint;
      return off;
    });
  }

  // ------------------------------------------------------------------ SVG

  function toSVG(part, opts) {
    const o = Object.assign({ kerf: 0, margin: 2, engrave: true, label: true }, opts || {});
    const loops = kerfLoops(part, o.kerf);
    const bb = GEO.bbox(loops);
    const M = o.margin;
    const w = bb.w + 2 * M, h = bb.h + 2 * M;
    // transform: x' = x - minX + M ; y' = (maxY - y) + M  (flip Y)
    const tx = x => N(x - bb.minX + M);
    const ty = y => N(bb.maxY - y + M);

    const pathOf = pts => {
      let s = `M ${tx(pts[0][0])} ${ty(pts[0][1])}`;
      for (let i = 1; i < pts.length; i++) s += ` L ${tx(pts[i][0])} ${ty(pts[i][1])}`;
      return s + ' Z';
    };

    const cutPaths = loops.map(l =>
      l.circleHint
        ? `    <circle cx="${tx(l.circleHint.cx)}" cy="${ty(l.circleHint.cy)}" r="${N(l.circleHint.r)}"/>`
        : `    <path d="${pathOf(l.pts)}"/>`
    ).join('\n');

    let engraveEls = '';
    if (o.engrave && part.engrave && part.engrave.length) {
      engraveEls = part.engrave.map(e => {
        if (e.kind === 'circle') return `    <circle cx="${tx(e.cx)}" cy="${ty(e.cy)}" r="${N(e.r)}"/>`;
        if (e.kind === 'line') return `    <path d="M ${tx(e.pts[0][0])} ${ty(e.pts[0][1])} L ${tx(e.pts[1][0])} ${ty(e.pts[1][1])}"/>`;
        if (e.kind === 'text' && o.label) {
          return `    <text x="${tx(e.x)}" y="${ty(e.y)}" font-size="${N(e.h)}" text-anchor="middle" `
            + `font-family="monospace" fill="none">${escapeXML(e.text)}</text>`;
        }
        return '';
      }).filter(Boolean).join('\n');
    }

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by GearForge — ${escapeXML(part.data && part.data.type || 'part')}${o.kerf ? ` | kerf ${o.kerf} mm compensated` : ''} -->
<svg xmlns="http://www.w3.org/2000/svg" width="${N(w)}mm" height="${N(h)}mm" viewBox="0 0 ${N(w)} ${N(h)}">
  <g id="CUT" fill="none" stroke="#ff0000" stroke-width="0.1">
${cutPaths}
  </g>
${engraveEls ? `  <g id="ENGRAVE" fill="none" stroke="#0000ff" stroke-width="0.1">\n${engraveEls}\n  </g>\n` : ''}</svg>
`;
  }

  function escapeXML(s) {
    return String(s).replace(/[<>&"']/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;' }[c]));
  }

  // ------------------------------------------------------------------ DXF

  function dxfPolyline(pts, layer) {
    const rows = ['0', 'POLYLINE', '8', layer, '66', '1', '70', '1'];
    for (const p of pts) {
      rows.push('0', 'VERTEX', '8', layer, '10', N(p[0]), '20', N(p[1]));
    }
    rows.push('0', 'SEQEND');
    return rows;
  }

  function toDXF(part, opts) {
    const o = Object.assign({ kerf: 0, engrave: true, label: true }, opts || {});
    const loops = kerfLoops(part, o.kerf);

    const rows = [
      '0', 'SECTION', '2', 'HEADER',
      '9', '$ACADVER', '1', 'AC1009',
      '9', '$INSUNITS', '70', '4',      // millimetres
      '9', '$MEASUREMENT', '70', '1',   // metric
      '0', 'ENDSEC',
      '0', 'SECTION', '2', 'TABLES',
      '0', 'TABLE', '2', 'LAYER', '70', '2',
      '0', 'LAYER', '2', 'CUT', '70', '0', '62', '1', '6', 'CONTINUOUS',
      '0', 'LAYER', '2', 'ENGRAVE', '70', '0', '62', '5', '6', 'CONTINUOUS',
      '0', 'ENDTAB', '0', 'ENDSEC',
      '0', 'SECTION', '2', 'ENTITIES',
    ];

    for (const l of loops) {
      if (l.circleHint) {
        rows.push('0', 'CIRCLE', '8', 'CUT',
          '10', N(l.circleHint.cx), '20', N(l.circleHint.cy), '40', N(l.circleHint.r));
      } else {
        rows.push(...dxfPolyline(l.pts, 'CUT'));
      }
    }

    if (o.engrave && part.engrave) {
      for (const e of part.engrave) {
        if (e.kind === 'circle') {
          rows.push('0', 'CIRCLE', '8', 'ENGRAVE', '10', N(e.cx), '20', N(e.cy), '40', N(e.r));
        } else if (e.kind === 'line') {
          rows.push('0', 'LINE', '8', 'ENGRAVE',
            '10', N(e.pts[0][0]), '20', N(e.pts[0][1]),
            '11', N(e.pts[1][0]), '21', N(e.pts[1][1]));
        } else if (e.kind === 'text' && o.label) {
          rows.push('0', 'TEXT', '8', 'ENGRAVE',
            '10', N(e.x), '20', N(e.y), '40', N(e.h), '1', String(e.text), '72', '1',
            '11', N(e.x), '21', N(e.y));
        }
      }
    }

    rows.push('0', 'ENDSEC', '0', 'EOF');
    return rows.join('\r\n') + '\r\n';
  }

  /** Plain-text dimension & inspection report. */
  function toReport(part, opts) {
    const o = opts || {};
    const lines = [`GearForge report — ${part.data.type}`, '='.repeat(50)];
    for (const [k, v] of Object.entries(part.data)) {
      if (k === 'type') continue;
      const label = k.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase());
      lines.push(`${label.padEnd(28)} ${typeof v === 'number' ? +v.toFixed(4) : v}`);
    }
    if (o.kerf) lines.push(`${'Kerf compensated'.padEnd(28)} ${o.kerf} mm`);
    if (part.warnings && part.warnings.length) {
      lines.push('', 'Notes:');
      for (const w of part.warnings) lines.push(`  [${w.level}] ${w.msg}`);
    }
    return lines.join('\n') + '\n';
  }

  const api = { toSVG, toDXF, toReport, kerfLoops };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else (global.GearForge = global.GearForge || {}).exporters = api;
})(typeof self !== 'undefined' ? self : this);
