/*
 * involute.js — standards-correct involute spur gearing for GearForge.
 *
 * External spur gears per ISO 21771 geometry with the DIN 867 / ISO 53 basic
 * rack (default profile A: ha*=1.00, hf*=1.25, rho_f*=0.38). Root fillets are
 * the exact envelope (trochoid) generated by the rack cutter's rounded tip
 * corner, so undercut on low tooth counts is reproduced correctly.
 *
 * Also: internal (ring) gears, racks, mesh/pair math, and inspection values
 * (span measurement Wk, measurement over pins M).
 *
 * Angles in radians internally; module in mm.
 */
(function (global) {
  'use strict';

  const GEO = (typeof module !== 'undefined' && module.exports)
    ? require('./geometry.js')
    : global.GearForge.geometry;

  const { arc, circle, dedupe, rotPts, mirrorY } = GEO;

  const inv = t => Math.tan(t) - t;

  /** Solve inv(a) = q for a in (0, pi/2) by Newton iteration. */
  function invInverse(q) {
    let a = Math.cbrt(3 * q); // good seed for small q
    for (let i = 0; i < 30; i++) {
      const f = Math.tan(a) - a - q;
      const df = Math.tan(a) * Math.tan(a);
      if (df < 1e-14) break;
      const step = f / df;
      a -= step;
      if (Math.abs(step) < 1e-14) break;
    }
    return a;
  }

  // ------------------------------------------------------------ parameters

  function normalizeParams(p) {
    const q = Object.assign({
      m: 2,            // module (mm)
      z: 20,           // tooth count
      alphaDeg: 20,    // pressure angle (deg)
      x: 0,            // profile shift coefficient
      haC: 1.0,        // addendum coefficient (of basic rack)
      hfC: 1.25,       // dedendum coefficient
      rhoC: 0.38,      // rack tip fillet radius coefficient (ISO 53 profile A)
      backlash: 0,     // circular backlash allowance -> tooth thinning ds (mm)
      tipShortC: 0,    // tip shortening coefficient k (subtracted from addendum)
    }, p || {});
    q.alpha = (q.alphaDeg * Math.PI) / 180;
    return q;
  }

  /** Fundamental radii & thicknesses for an external gear. */
  function externalGearData(p) {
    const { m, z, alpha, x, haC, hfC, rhoC, backlash, tipShortC } = p;
    const rp = (m * z) / 2;
    const rb = rp * Math.cos(alpha);
    const ra = rp + m * (haC + x - tipShortC);
    const rf = rp - m * (hfC - x);
    const s = m * (Math.PI / 2 + 2 * x * Math.tan(alpha)) - backlash; // pitch tooth thickness
    return { rp, rb, ra, rf, s, psi: s / (2 * rp) };
  }

  // -------------------------------------------- external tooth construction

  /**
   * Involute flank polyline for the +theta side of a tooth centered on
   * theta = 0, from radius r0 (>= rb) out to ra. Ordered root -> tip.
   */
  function involuteFlank(g, p, r0, nPts) {
    const { rb, ra, psi } = g;
    const t0 = Math.sqrt(Math.max(0, (r0 / rb) ** 2 - 1)); // roll parameter tan(alpha_r)
    const t1 = Math.sqrt(Math.max(0, (ra / rb) ** 2 - 1));
    const n = nPts || 36;
    const pts = [];
    for (let i = 0; i <= n; i++) {
      // quadratic roll-angle spacing: denser near the root where curvature is high
      const u = i / n;
      const t = t0 + (t1 - t0) * u * (2 - u);
      const r = rb * Math.sqrt(1 + t * t);
      const th = psi + inv(p.alpha) - inv(Math.atan(t));
      pts.push([r * Math.cos(th), r * Math.sin(th)]);
    }
    return pts; // ordered from small r (theta large) to tip
  }

  /**
   * Root-fillet trochoid: envelope of the rack cutter tip-corner circle.
   *
   * Rack coordinates: xi along the pitch line, eta radially outward from the
   * gear center measured from the pitch line. The rack space half-width at
   * height eta is  w(eta) = a - eta*tan(alpha)  with  a = s/2  (the space is
   * the negative of the gear tooth). The cutter tip cuts down to
   * eta_tip = -(hfC - x)m and the corner circle (radius rho) sits at:
   *   eta_c = eta_tip + rho
   *   xi_c  = a - eta_c*tan(alpha) + rho/cos(alpha)
   * As the gear rolls (rotation phi, rack translates rp*phi), the corner
   * center traces C(phi). By the fundamental law of gearing the contact
   * normal passes through the instantaneous pitch point I(phi), so the cut
   * surface (envelope of the corner circle) is exactly
   *   P(phi) = C(phi) + rho * unit(C(phi) - I(phi)),
   * with I(phi) = (-rp*sin phi, rp*cos phi) in the gear frame. At the
   * aligned instant this bottoms out exactly on the root circle.
   *
   * Returns polyline ordered from the root circle up toward the flank,
   * located on the +theta side of a tooth centered at theta = 0.
   */
  function rootFilletTrochoid(g, p, nPts) {
    const { rp, s } = g;
    const { m, alpha, hfC, rhoC, x } = p;
    const rho = rhoC * m;
    const a = s / 2;
    const etaTip = -(hfC - x) * m;
    const etaC = etaTip + rho;
    const xiC = a - etaC * Math.tan(alpha) + rho / Math.cos(alpha);

    // center path in gear frame (tooth centered at top, theta = pi/2)
    const center = phi => {
      const X = xiC + rp * phi;
      const Y = rp + etaC;
      const c = Math.cos(phi), s2 = Math.sin(phi);
      return [c * X - s2 * Y, s2 * X + c * Y];
    };

    // Generation zone: corner passes over the top near phi0 = -xiC/rp.
    const phi0 = -xiC / rp;
    const span = (2.4 * (Math.abs(etaTip) + rho)) / (rp * Math.max(Math.tan(alpha), 0.18))
      + Math.PI / p.z;
    const n = nPts || 90;
    const raw = [];
    for (let i = 0; i <= n; i++) {
      const phi = phi0 - span / 2 + (span * i) / n;
      const C = center(phi);
      const Ix = -rp * Math.sin(phi), Iy = rp * Math.cos(phi); // pitch point, gear frame
      const dx = C[0] - Ix, dy = C[1] - Iy;
      const dl = Math.hypot(dx, dy);
      if (dl < 1e-12) continue;
      raw.push([C[0] + (rho * dx) / dl, C[1] + (rho * dy) / dl]);
    }

    // Rotate frame so the tooth center is at theta = 0. The +xi rack flank
    // generates the flank on the -theta' side; mirror to get the +theta side.
    // Returned RAW (no branch selection): the caller treats these points as
    // material-removal samples and takes per-radius minima, which handles
    // undercut loops and cross-centerline cuts without any branch logic.
    return rotPts(raw, -Math.PI / 2).map(q => [q[0], -q[1]]);
  }

  /**
   * Form radius: lowest radius generated by the STRAIGHT flank of the rack
   * (below it, only the tip corner cuts). hf_eff is the depth of the
   * flank/corner tangency point below the pitch line.
   */
  function formRadius(g, p) {
    const { m, alpha, hfC, rhoC, x } = p;
    const hfEff = (hfC - x) * m - rhoC * m * (1 - Math.sin(alpha));
    const u = g.rp * Math.sin(alpha) - hfEff / Math.sin(alpha);
    if (u <= 0) return g.rb * (1 + 1e-9);
    return Math.max(g.rb * (1 + 1e-9), Math.sqrt(g.rb * g.rb + u * u));
  }

  /**
   * Build the closed outline of one external spur gear (CCW, tooth #0
   * centered on the +X axis).
   *
   * Root construction: the material boundary at radius r is the MINIMUM
   * half-angle reached by any cutter element at that radius —
   *   - the rack tip-corner envelope (trochoid), sampled raw and binned by
   *     radius, with points beyond the space centerline folded back in
   *     (they represent the adjacent corner's symmetric cut), and
   *   - the involute from the straight flank, valid only above formRadius.
   * Taking per-radius minima handles undercut loops, tangent joins and
   * cross-centerline cuts in one uniform way (no branch/intersection logic).
   */
  function externalGearOutline(p, g) {
    const spaceAng = Math.PI / p.z;
    const rForm = formRadius(g, p);
    const thFlank = r => g.psi + inv(p.alpha) - inv(Math.acos(Math.min(1, g.rb / r)));

    // ---- corner-envelope minima, binned by radius over [rf, ra]
    const raw = rootFilletTrochoid(g, p, 700);
    const NB = 400;
    const rSpan = g.ra - g.rf;
    const binTh = new Array(NB).fill(Infinity);
    // A candidate participates in the +half boundary only inside the
    // fundamental domain [0, spaceAng]; cuts outside it belong to the
    // neighbouring halves, which are covered by symmetry.
    const noteAt = (r, th) => {
      if (th < 0 || th > spaceAng + 1e-9 || r >= g.ra) return;
      const b = Math.floor(((r - g.rf) / rSpan) * NB);
      if (b < 0 || b >= NB) return;
      if (th < binTh[b]) binTh[b] = th;
    };
    for (const q of raw) {
      const r = Math.hypot(q[0], q[1]);
      const th = Math.atan2(q[1], q[0]);
      noteAt(r, th);                        // this corner
      noteAt(r, 2 * spaceAng - th);         // adjacent corner (mirror fold)
      noteAt(r, -th);                       // opposite corner reaching across
    }
    const rOfBin = b => g.rf + ((b + 0.5) / NB) * rSpan;

    // ---- walk bins from the root upward while the corner cut is the
    //      boundary; switch to the analytic involute where it takes over.
    const half = []; // +theta side, ordered space-centerline -> tip
    let b = 0;
    while (b < NB && binTh[b] === Infinity) b++;
    if (b >= NB) throw new Error('Root fillet generation failed (no envelope coverage).');
    const startTh = Math.min(spaceAng, binTh[b]);
    if (startTh <= 1e-6) throw new Error('Tooth is destroyed by undercut — increase z or profile shift.');
    // root land arc at rf from the space centerline to the fillet start
    if (startTh < spaceAng - 1e-6) half.push(...arc(0, 0, g.rf, spaceAng, startTh, 0.02));

    let lastCorner = Infinity;
    let switched = false, rSwitch = g.ra;
    for (; b < NB; b++) {
      const r = rOfBin(b);
      let th = binTh[b];
      if (th === Infinity) th = lastCorner; // sparse bin: carry the last value
      if (th === Infinity) continue;
      lastCorner = th;
      const tf = r >= rForm ? thFlank(r) : Infinity;
      if (tf <= th + 1e-7) { switched = true; rSwitch = Math.max(r, g.rb * (1 + 1e-9)); break; }
      half.push([r * Math.cos(th), r * Math.sin(th)]);
    }
    if (!switched) rSwitch = Math.max(rForm, g.rb * (1 + 1e-9));

    // analytic involute from the switch radius to the tip (exact flank)
    if (rSwitch < g.ra - 1e-9) half.push(...involuteFlank(g, p, rSwitch, 40));

    // simplify: the radius bins are far denser than needed; 2 µm tolerance
    // keeps the profile true while making downstream kerf offsets robust.
    const halfSimple = GEO.rdp(dedupe(half, 1e-9), 0.002);
    half.length = 0;
    half.push(...halfSimple);

    // tip: from the flank end (+theta side) across theta=0 to the mirror
    const tipEnd = half[half.length - 1];
    const tipAng = Math.atan2(tipEnd[1], tipEnd[0]);

    // one full tooth, ordered CW in theta (from +spaceAng to -spaceAng):
    const tooth = half.slice(); // space centerline -> tip (+ side)
    if (tipAng > 1e-9) tooth.push(...arc(0, 0, g.ra, tipAng, -tipAng, 0.02).slice(1));
    tooth.push(...mirrorY(half).slice(tipAng > 1e-9 ? 0 : 1));

    // replicate around the gear; theta runs downward within each tooth, so
    // step teeth in -theta order to keep the chain contiguous, then reverse
    // the final loop to CCW.
    const all = [];
    for (let k = 0; k < p.z; k++) {
      all.push(...rotPts(tooth, -(2 * Math.PI * k) / p.z));
    }
    const outline = dedupe(all, 1e-7);
    outline.reverse(); // CCW
    return { pts: outline, rForm, rSwitch };
  }

  // ----------------------------------------------------- inspection values

  /** Tooth thickness (arc) at arbitrary radius r on the involute. */
  function toothThicknessAt(g, p, r) {
    const ar = Math.acos(Math.min(1, g.rb / r));
    return 2 * r * (g.psi + inv(p.alpha) - inv(ar));
  }

  /** Span measurement (base tangent length) over k teeth. */
  function spanMeasurement(p, k) {
    const { m, z, alpha, x } = p;
    return m * Math.cos(alpha) * (Math.PI * (k - 0.5) + z * inv(alpha))
      + 2 * x * m * Math.sin(alpha);
  }

  /** Recommended number of teeth to span. */
  function spanTeethCount(p) {
    const { z, alpha, x } = p;
    const k = Math.round(z * ((Math.tan(alpha) - inv(alpha)) / Math.PI)
      - (2 * x * Math.tan(alpha)) / Math.PI + 0.5) || 1;
    return Math.max(2, k);
  }

  /** Measurement over two pins (external gear). Returns {M, dPin, alphaM}. */
  function measurementOverPins(p, g, dPin) {
    const d = 2 * g.rp, db = 2 * g.rb;
    dPin = dPin || Math.round(1.68 * p.m * 100) / 100; // common pin ~1.68m for 20 deg
    const q = g.s / d + inv(p.alpha) + dPin / (db) - Math.PI / p.z;
    if (q <= 0) return { M: NaN, dPin, alphaM: NaN };
    const aM = invInverse(q);
    const Rc = g.rb / Math.cos(aM);
    const even = p.z % 2 === 0;
    const M = even ? 2 * Rc + dPin : 2 * Rc * Math.cos(Math.PI / (2 * p.z)) + dPin;
    return { M, dPin, alphaM: aM, Rc };
  }

  // ----------------------------------------------------------- pair / mesh

  /**
   * Mesh data for an external-external pair.
   * Returns {alphaW, aw, a0, i, epsAlpha, sa1, sa2}.
   */
  function meshExternal(p1, p2) {
    const g1 = externalGearData(p1), g2 = externalGearData(p2);
    const m = p1.m, alpha = p1.alpha;
    const invAw = inv(alpha) + (2 * (p1.x + p2.x) * Math.tan(alpha)) / (p1.z + p2.z);
    const alphaW = invInverse(invAw);
    const a0 = (m * (p1.z + p2.z)) / 2;
    const aw = (a0 * Math.cos(alpha)) / Math.cos(alphaW);
    const ga = r => Math.sqrt(Math.max(0, r.ra * r.ra - r.rb * r.rb));
    const epsAlpha = (ga(g1) + ga(g2) - aw * Math.sin(alphaW))
      / (Math.PI * m * Math.cos(alpha));
    return { alphaW, aw, a0, i: p2.z / p1.z, epsAlpha, g1, g2 };
  }

  // -------------------------------------------------------------- warnings

  function externalWarnings(p, g) {
    const w = [];
    const zMin = (2 * (p.haC - p.x)) / Math.sin(p.alpha) ** 2;
    if (p.z < zMin - 1e-9) {
      w.push({
        level: 'warn',
        msg: `Undercut: z=${p.z} < z_min≈${zMin.toFixed(1)} for x=${p.x}. The root is `
          + `generated correctly (trochoid) but the tooth is weakened; consider profile shift `
          + `x ≥ ${((zMin ? (p.haC - p.z * Math.sin(p.alpha) ** 2 / 2) : 0)).toFixed(2)}.`,
      });
    }
    const aa = Math.acos(Math.min(1, g.rb / g.ra));
    const sa = 2 * g.ra * (g.psi + inv(p.alpha) - inv(aa));
    if (sa <= 0) {
      w.push({ level: 'error', msg: `Pointed tooth tip (sa ≤ 0). Reduce profile shift or addendum.` });
    } else if (sa < 0.25 * p.m) {
      w.push({ level: 'warn', msg: `Thin tooth tip: sa=${sa.toFixed(3)} mm < 0.25·m. Consider tip shortening.` });
    }
    if (g.rf > g.rb) {
      w.push({ level: 'info', msg: `Root circle above base circle — whole flank is involute (no undercut region possible).` });
    }
    return { warnings: w, sa };
  }

  // ------------------------------------------------------------ part build

  /**
   * Build a complete external spur gear Part.
   * extra: {bore: {type:'none'|'round'|'d'|'hex'|'square'|'key', d, flatDepth, af},
   *         boltCircle: {n, d, bcd}, kerf, label}
   */
  function buildExternalGear(params, extra) {
    const p = normalizeParams(params);
    const g = externalGearData(p);
    const ex = extra || {};
    const warnList = [];

    if (p.z < 4) throw new Error('Tooth count must be ≥ 4');
    if (g.rf <= 0.1) throw new Error('Root radius ≤ 0 — reduce dedendum or increase z·m');

    const { warnings, sa } = externalWarnings(p, g);
    if (sa <= 0) {
      throw new Error(`Pointed tooth tip (sa=${sa.toFixed(3)} mm ≤ 0) — reduce profile shift, `
        + `addendum, or use tip shortening.`);
    }
    warnList.push(...warnings);

    const { pts } = externalGearOutline(p, g);
    const loops = [{ pts, isHole: false }];

    addBore(loops, ex, g.rf, warnList);
    addBoltCircle(loops, ex, g.rf, warnList);
    kerfWarnings(ex, p.rhoC * p.m, warnList);

    const k = spanTeethCount(p);
    const pins = measurementOverPins(p, g);
    const data = {
      type: 'External spur gear',
      module: p.m, teeth: p.z, pressureAngleDeg: p.alphaDeg, profileShift: p.x,
      pitchDia: 2 * g.rp, baseDia: 2 * g.rb, tipDia: 2 * g.ra, rootDia: 2 * g.rf,
      toothThicknessPitch: g.s, tipThickness: sa,
      circularPitch: Math.PI * p.m,
      spanTeeth: k, spanMeasurement: spanMeasurement(p, k),
      pinDia: pins.dPin, measurementOverPins: pins.M,
      backlashAllowance: p.backlash,
    };

    return {
      cut: loops,
      engrave: engraveSet(2 * g.rp, ex.label !== undefined ? ex.label
        : `m${p.m} z${p.z} α${p.alphaDeg}° x${p.x}`),
      data, warnings: warnList, geo: { p, g },
    };
  }

  /** Internal (ring) gear Part. extra: {rim (mm), kerf, boltCircle, label} */
  function buildInternalGear(params, extra) {
    const p = normalizeParams(params);
    const ex = extra || {};
    const warnList = [];
    const { m, z, alpha, x } = p;
    if (z < 12) throw new Error('Internal gears need z ≥ 12');

    const rp = (m * z) / 2;
    const rb = rp * Math.cos(alpha);
    const rTip = rp - m * (p.haC - x);   // inner (addendum) radius of teeth
    const rRoot = rp + m * (p.hfC + x);  // outer (dedendum) radius
    const s = m * (Math.PI / 2 - 2 * x * Math.tan(alpha)) - p.backlash;
    const psi = s / (2 * rp);
    if (rTip <= rb * 1.001) {
      warnList.push({ level: 'warn', msg: 'Tooth tip near/below base circle — tip trimmed to base circle.' });
    }
    const rIn = Math.max(rTip, rb * 1.001);

    // flank on +theta side of a tooth centered at theta=0. Internal teeth
    // widen outward: theta(r) = psi - inv(alpha) + inv(alpha_r).
    const flank = [];
    const n = 36;
    const t0 = Math.sqrt((rIn / rb) ** 2 - 1);
    const t1 = Math.sqrt((rRoot / rb) ** 2 - 1);
    for (let i = 0; i <= n; i++) {
      const t = t0 + ((t1 - t0) * i) / n;
      const r = rb * Math.sqrt(1 + t * t);
      const th = psi - inv(alpha) + inv(Math.atan(t));
      flank.push([r * Math.cos(th), r * Math.sin(th)]);
    }

    // root fillet: simple tangent arc between flank end and root circle,
    // clipped strictly inside this tooth's half-space so adjacent teeth
    // can never overlap at the space centerline.
    const rho = 0.3 * m;
    const spaceAng = Math.PI / z;
    const filletPts = internalRootFillet(flank, rRoot, rho, z)
      .filter(q => Math.atan2(q[1], q[0]) < spaceAng - 1e-6);
    const half = [];
    // from tooth center at tip: arc across tip handled at assembly; build
    // +theta half from tip corner to space center at root circle.
    half.push(...flank, ...filletPts);
    const endAng = Math.atan2(half[half.length - 1][1], half[half.length - 1][0]);
    if (endAng < spaceAng - 1e-6) half.push(...arc(0, 0, rRoot, endAng, spaceAng, 0.02).slice(1));

    // full tooth boundary ordered with increasing theta: mirror(-side) + tip arc + half
    const tipHalfAng = Math.atan2(flank[0][1], flank[0][0]);
    const minus = mirrorY(half); // ordered from space center (-) to tip corner (-)
    const tooth = [];
    tooth.push(...minus);
    if (tipHalfAng > 1e-9) tooth.push(...arc(0, 0, rIn, -tipHalfAng, tipHalfAng, 0.02).slice(1));
    tooth.push(...half.slice(1));

    const all = [];
    for (let k2 = 0; k2 < z; k2++) all.push(...rotPts(tooth, (2 * Math.PI * k2) / z));
    let toothLoop = dedupe(all, 1e-7);
    // this loop bounds the *hole* of the ring gear; hole loops face inward.
    const rim = ex.rim || Math.max(3 * m, 5);
    const rOut = rRoot + rim;
    const loops = [
      { pts: circle(0, 0, rOut, Math.max(120, z * 6)), isHole: false },
      { pts: toothLoop, isHole: true },
    ];
    addBoltCircle(loops, ex, rOut, warnList, rRoot + rim * 0.5);

    const data = {
      type: 'Internal (ring) gear',
      module: m, teeth: z, pressureAngleDeg: p.alphaDeg, profileShift: x,
      pitchDia: 2 * rp, baseDia: 2 * rb, tipDia: 2 * rIn, rootDia: 2 * rRoot,
      outerDia: 2 * rOut, toothThicknessPitch: s, circularPitch: Math.PI * m,
      backlashAllowance: p.backlash,
    };
    return {
      cut: loops,
      engrave: engraveSet(2 * rp, ex.label !== undefined ? ex.label : `ring m${m} z${z}`),
      data, warnings: warnList,
      geo: { p, g: { rp, rb, ra: rIn, rf: rRoot, s, psi } },
    };
  }

  function internalRootFillet(flank, rRoot, rho, z) {
    // tangent line at the flank end
    const A = flank[flank.length - 2], B = flank[flank.length - 1];
    let tx = B[0] - A[0], ty = B[1] - A[1];
    const tl = Math.hypot(tx, ty); tx /= tl; ty /= tl;
    // normal pointing into the tooth space (increasing theta side)
    let nx = -ty, ny = tx;
    const cross = B[0] * ty - B[1] * tx;
    if (cross < 0) { nx = -nx; ny = -ny; }
    // center candidate: offset from B along normal by rho, then pull to |C| = rRoot - rho
    let C = [B[0] + nx * rho, B[1] + ny * rho];
    const cl = Math.hypot(C[0], C[1]);
    const target = rRoot - rho;
    C = [C[0] * (target / cl), C[1] * (target / cl)];
    // arc from tangency-with-flank (approx: nearest point on circle to B) to
    // the radially outward point (tangency with root circle)
    const a0 = Math.atan2(B[1] - C[1], B[0] - C[0]);
    const a1 = Math.atan2(C[1], C[0]); // outward direction => tangency with root circle
    let sweep = a1 - a0;
    while (sweep > Math.PI) sweep -= 2 * Math.PI;
    while (sweep < -Math.PI) sweep += 2 * Math.PI;
    void z;
    return arc(C[0], C[1], rho, a0, a0 + sweep, 0.05).slice(1);
  }

  /** Rack Part. params: m, alphaDeg, teeth (count), height (blank below root), backlash */
  function buildRack(params, extra) {
    const p = normalizeParams(params);
    const ex = extra || {};
    const n = Math.max(2, Math.round(params.teeth || 10));
    const { m, alpha } = p;
    const pitch = Math.PI * m;
    const ha = p.haC * m, hf = p.hfC * m;
    const rTip = 0.25 * m, rRoot = p.rhoC * m;
    const s = pitch / 2 - (p.backlash || 0); // tooth thickness at reference line
    const body = ex.height || 3 * m;

    // one tooth profile, reference line at y=0, tooth pointing +y.
    // half-widths: at reference: s/2; at tip: s/2 - ha*tan(alpha); at root: s/2 + hf*tan(alpha)
    const tanA = Math.tan(alpha), cosA = Math.cos(alpha), sinA = Math.sin(alpha);
    const wTip = s / 2 - ha * tanA;
    if (wTip <= rTip * cosA * 0.5) throw new Error('Rack tip land collapses — reduce addendum or pressure angle');

    // Corner fillet centers for the right flank of a tooth centered at x=0.
    // Flank line: x = s/2 - y·tanα, unit normal (cosα, sinα). Each fillet
    // circle is tangent to the flank line and to its land (y=ha / y=-hf).
    const tipCenter = [s / 2 - ha * tanA - rTip * (1 / cosA - tanA), ha - rTip];
    const rootCenter = [s / 2 + hf * tanA + rRoot * (1 / cosA - tanA), -hf + rRoot];
    const tipTangFlank = [tipCenter[0] + rTip * cosA, tipCenter[1] + rTip * sinA];
    const rootTangFlank = [rootCenter[0] - rRoot * cosA, rootCenter[1] - rRoot * sinA];

    const half = [];
    half.push([0, ha]); // tip center
    half.push([tipCenter[0], ha]);
    // tip corner arc from top (angle 90°) to flank tangent
    const aFlank = Math.atan2(tipTangFlank[1] - tipCenter[1], tipTangFlank[0] - tipCenter[0]);
    half.push(...arc(tipCenter[0], tipCenter[1], rTip, Math.PI / 2, aFlank, 0.06).slice(1));
    // flank down to root fillet tangency
    half.push(rootTangFlank);
    // root fillet from flank tangency to root land (angle -90° at bottom)
    const aFl2 = Math.atan2(rootTangFlank[1] - rootCenter[1], rootTangFlank[0] - rootCenter[0]);
    half.push(...arc(rootCenter[0], rootCenter[1], rRoot, aFl2, -Math.PI / 2, 0.06).slice(1));
    half.push([pitch / 2, -hf]); // root land to space center

    // full tooth: mirror + half
    const left = half.map(q => [-q[0], q[1]]).reverse();
    const tooth = left.concat(half.slice(1));

    // rack outline: teeth left→right along top, then rectangle back
    const top = [];
    for (let i = 0; i < n; i++) {
      const dx = i * pitch;
      for (const q of tooth) top.push([q[0] + dx, q[1]]);
    }
    const x0 = -pitch / 2, x1 = (n - 1) * pitch + pitch / 2;
    const yBot = -hf - body;
    const outline = dedupe([[x0, yBot], [x0, -hf]].concat(top, [[x1, -hf], [x1, yBot]]));

    const loops = [{ pts: GEO.ensureWinding(outline, true), isHole: false }];
    if (ex.holes && ex.holes.n > 0) {
      for (let i = 0; i < ex.holes.n; i++) {
        const cx = x0 + ((x1 - x0) * (i + 0.5)) / ex.holes.n;
        loops.push({ pts: circle(cx, yBot + body / 2, ex.holes.d / 2, 40), isHole: true, circleHint: { cx, cy: yBot + body / 2, r: ex.holes.d / 2 } });
      }
    }
    const data = {
      type: 'Rack', module: m, teeth: n, pressureAngleDeg: p.alphaDeg,
      circularPitch: pitch, length: x1 - x0, height: ha + hf + body,
      addendum: ha, dedendum: hf, toothThicknessRef: s,
    };
    return {
      cut: loops,
      engrave: [{ kind: 'line', pts: [[x0, 0], [x1, 0]] }],
      data, warnings: [], geo: { p },
    };
  }

  // ------------------------------------------------------------- utilities

  function addBore(loops, ex, maxR, warnList) {
    const b = ex.bore;
    if (!b || b.type === 'none' || !b.type) return;
    let loop = null, note = null;
    if (b.type === 'round' && b.d > 0) loop = GEO.boreRound(b.d);
    else if (b.type === 'd' && b.d > 0) loop = GEO.boreD(b.d, b.flatDepth || b.d * 0.1);
    else if (b.type === 'hex' && b.af > 0) loop = GEO.borePolygon(b.af, 6);
    else if (b.type === 'square' && b.af > 0) loop = GEO.borePolygon(b.af, 4);
    else if (b.type === 'key' && b.d > 0) {
      const r = GEO.boreKeyed(b.d);
      loop = r.loop;
      if (r.key) note = `Keyway DIN 6885: ${r.key.b}×${r.key.h} key, hub depth t2=${r.key.t2} (slot to Ø${(b.d + 2 * r.key.t2).toFixed(2)})`;
      else warnList.push({ level: 'warn', msg: `No DIN 6885 key size for Ø${b.d} — plain bore used.` });
    }
    if (!loop) return;
    const boreMax = Math.max(...loop.pts.map(q => Math.hypot(q[0], q[1])));
    if (boreMax >= maxR * 0.85) {
      warnList.push({ level: 'warn', msg: `Bore is ${(100 * boreMax / maxR).toFixed(0)}% of the root radius — thin web.` });
    }
    if (boreMax >= maxR) throw new Error('Bore larger than the part.');
    if (b.type === 'round') loop.circleHint = { cx: 0, cy: 0, r: b.d / 2 };
    loops.push(loop);
    if (note) warnList.push({ level: 'info', msg: note });
  }

  function addBoltCircle(loops, ex, maxR, warnList, forcedR) {
    const bc = ex.boltCircle;
    if (!bc || !(bc.n > 0) || !(bc.d > 0) || !(bc.bcd > 0)) return;
    void forcedR;
    if (bc.bcd / 2 + bc.d / 2 >= maxR) {
      warnList.push({ level: 'error', msg: 'Bolt circle extends past the part — holes skipped.' });
      return;
    }
    loops.push(...GEO.boltCircle(bc.n, bc.d, bc.bcd, bc.startDeg || 0));
  }

  function kerfWarnings(ex, rho, warnList) {
    if (ex.kerf && ex.kerf / 2 > 0.3 * rho) {
      warnList.push({
        level: 'warn',
        msg: `Kerf/2 (${(ex.kerf / 2).toFixed(3)}) is large vs. the root fillet radius (${rho.toFixed(2)}) — offset accuracy degrades in the root.`,
      });
    }
  }

  function engraveSet(pitchDia, label) {
    const out = [
      { kind: 'circle', cx: 0, cy: 0, r: pitchDia / 2 },
      { kind: 'line', pts: [[-pitchDia * 0.06, 0], [pitchDia * 0.06, 0]] },
      { kind: 'line', pts: [[0, -pitchDia * 0.06], [0, pitchDia * 0.06]] },
    ];
    if (label) out.push({ kind: 'text', x: 0, y: -pitchDia * 0.12, h: Math.max(2, pitchDia * 0.045), text: label });
    return out;
  }

  const api = {
    inv, invInverse, normalizeParams, externalGearData,
    involuteFlank, rootFilletTrochoid, formRadius, externalGearOutline,
    toothThicknessAt, spanMeasurement, spanTeethCount, measurementOverPins,
    meshExternal, externalWarnings,
    buildExternalGear, buildInternalGear, buildRack,
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else (global.GearForge = global.GearForge || {}).involute = api;
})(typeof self !== 'undefined' ? self : this);
